### ISSUE TITLE
Is there a way to exclude certain commits based on a pattern?

### ISSUE THREAD

**Issue by FrancescoBonizzi** [ardalanamini/auto-changelog#153]
Consider these commits:

<img width="391" alt="image" src="https://github.com/ardalanamini/auto-changelog/assets/11348479/178dc332-555c-4f32-9523-54ed405873ee">

They are automatic, usually I forget to amend their message to add a prefix. I'd like to exclude those from the changelog, as they appear like this:

<img width="867" alt="image" src="https://github.com/ardalanamini/auto-changelog/assets/11348479/1328e118-b793-475b-93e7-e18ab899984f">

Is there a way to configure the action to exclude it? (I would exclude this if it starts with "Merge"

**Comment by ardalanamini** [comment]
@FrancescoBonizzi Thanks for submitting this issue;
This case is a bug, but I'll probably add the exclude pattern option as well 🤔
