### ISSUE TITLE
Multiline commit messages are dropped

### ISSUE THREAD

**Issue by laughedelic** [ardalanamini/auto-changelog#3]
Hi! Thanks for the useful action!

I noticed that some of my commits don't make it to the changelog. I found that it happens to all commits with multiline messages. I suspect that the problem is in the commit regex:

https://github.com/ardalanamini/auto-changelog/blob/e2ed19a3f16dd561a623e4fd6ecd9a907c4fd734/src/changelog.ts#L95

But I'm not sure how to fix it. Could you look into it?

**Comment by ardalanamini** [comment]
@laughedelic Hi, Thank you for submitting the issue

I think based on the below format (if it also is the case for you) we can just use the first line and ignore the rest:

```git
type(optional category): description [optional flag]

[optional body]

[optional footer(s)]
```

Please let me know If this approach works for you or not

**Comment by laughedelic** [comment]
Yes, this is what I'd expect as well: I want to see only the message summary in the changelog, so the only using the first line of the commit message totally makes sense 👍

**Comment by ardalanamini** [comment]
@laughedelic Update the version you're using and it should be fixed

```yaml
uses: ardalanamini/auto-changelog@v1.0.1
```
