### ISSUE TITLE
Can I make the generated changelog start after the last release?

### ISSUE THREAD

**Issue by bigfacewo** [ardalanamini/auto-changelog#5]
I want to cooperate with the automatic creation of release action, but every time the complete changelog is generated, can I only generate the changelog after the last release?

**Comment by ardalanamini** [comment]
@bigfacewo What version are you using? there don't seem to be any issues as can be seen from [here](https://github.com/ardalanamini/prototyped.js/runs/3831479188?check_suite_focus=true), it worked as expected!
can you share more details on your config and output?

**Comment by ardalanamini** [comment]
Due to lack of response in a long time and information indicating existence of a bug, I'll close this issue for now!

If you still have issues, feel free to reopen or submit another issue 👍🏻
