### ISSUE TITLE
Action just doesn't work.

### ISSUE THREAD

**Issue by Rukkaitto** [ardalanamini/auto-changelog#6]
I have copy pasted the example code, commited with the message "ci: Testing ci", and the action just does not output anything.
`
::set-output name=changelog::
##[debug]steps.generate-changelog.outputs.changelog=
`

**Comment by ardalanamini** [comment]
@Rukkaitto What version are you using? there don't seem to be any issues as can be seen from [here](https://github.com/ardalanamini/prototyped.js/runs/3831479188?check_suite_focus=true), it worked as expected!
can you share more details on your config and output?
